// 表单配置示例
import type { FormConfig } from "~/types/form";

export const BASE_FORM_CONFIG: FormConfig = {
  layout: "horizontal",
  labelWidth: "120px",
  fields: [
    {
      key: "name",
      label: "名前",
      type: "text",
      value: "王 利艳",
      required: true,
    },
    {
      key: "kanaName",
      label: "名前（カタカナ）",
      type: "text",
      value: "オウ リエン",
      required: true,
    },
    {
      key: "birthDate",
      label: "生年月日",
      type: "date",
      placeholder: "YYYY年MM月DD日",
      required: true,
    },
    {
      key: "age",
      label: "年齢",
      type: "text",
      value: "○○歳",
      required: true,
    },
    {
      key: "gender",
      label: "性別",
      type: "radio",
      value: "女性",
      options: [
        { label: "男性", value: "男性" },
        { label: "女性", value: "女性" },
      ],
      required: true,
    },
    {
      key: "hireDate",
      label: "入社日",
      type: "date",
      placeholder: "YYYY年MM月DD日",
      required: true,
    },
    {
      key: "serviceYears",
      label: "勤務年数",
      type: "text",
      value: "14年4ヶ月",
      required: true,
    },
    {
      key: "employeeNumber",
      label: "社員番号",
      type: "text",
      value: "6",
      required: true,
    },
    {
      key: "hasSpouse",
      label: "配偶者",
      type: "radio",
      value: "有",
      options: [
        { label: "有", value: "有" },
        { label: "無", value: "無" },
      ],
      required: true,
    },
    {
      key: "isSingle",
      label: "寡婦/ひとり親",
      type: "radio",
      value: "該当対象外",
      options: [
        { label: "該当する", value: "該当する" },
        { label: "該当対象外", value: "該当対象外" },
      ],
      required: true,
      tip: "寡婦は夫と死別した後婚姻していない場合、ひとり親は婚姻をしていない親の場合で、 所得や扶養親族等の条件を満たす方です。",
      tipLink: "https://www.baidu.com",
    },
    {
      key: "isDisabled",
      label: "障害",
      type: "radio",
      value: "該当対象外",
      options: [
        { label: "該当する", value: "該当する" },
        { label: "該当対象外", value: "該当対象外" },
      ],
      required: true,
      tip: "該当する障害者は所得税法上で定められています。また、特別障害者は、重度の障害のある方です。詳しくはこちら",
    },
    {
      key: "isPartTime",
      label: "勤労学生",
      type: "radio",
      value: "該当しない",
      options: [
        { label: "該当する", value: "該当する" },
        { label: "該当しない", value: "該当しない" },
      ],
      required: true,
      tip: "2026年12月31日時点で、合計所得金額が85万円以下になる見込みの学生が該当します。詳しくはこちら",
    },
    {
      key: "employmentType",
      label: "雇用形態",
      type: "select",
      value: "社員",
      options: [
        { label: "社員", value: "社員" },
        { label: "契約社員", value: "契約社員" },
        { label: "アルバイト", value: "アルバイト" },
      ],
      required: true,
      tip: "雇用「役員」にするとfreee会計に作成される給与の取引の勘定科目が「役員報酬」となります。形態",
    },
    {
      key: "position",
      label: "肩書",
      type: "text",
      value: "部長",
      required: true,
    },
    {
      key: "insuranceNumber",
      label: "基礎年金番号",
      type: "text",
      value: "S0988008886",
      required: true,
    },
  ],
};

export const RESIDENTIAL_ADDRESS_FORM_CONFIG: FormConfig = {
  layout: "horizontal",
  labelWidth: "120px",
  fields: [
    {
      key: "postalCode",
      label: "郵便番号",
      type: "text",
      value: "125-0024",
      required: true,
    },
    {
      key: "prefecture",
      label: "都道府県",
      type: "text",
      value: "東京都",
      required: true,
    },
    {
      key: "address",
      label: "市区町村以降の住所",
      type: "text",
      value: "葛飾区新小岩３丁目６",
      required: true,
    },
    {
      key: "residentialStatus",
      label: "2026年時点での世帯",
      type: "text",
      value: "本人",
      required: true,
    },
    {
      key: "residentialOwnerName",
      label: "世帯主の名前",
      type: "text",
      value: "王 利艶",
      required: true,
    },
  ],
};

export const CURRENT_RESIDENCE_FORM_CONFIG: FormConfig = {
  layout: "horizontal",
  labelWidth: "120px",
  fields: [
    {
      key: "postalCode",
      label: "郵便番号",
      type: "text",
      value: "125-0024",
      required: true,
    },
    {
      key: "prefecture",
      label: "都道府県",
      type: "text",
      value: "東京都",
      required: true,
    },
    {
      key: "address",
      label: "市区町村以降の住所",
      type: "text",
      value: "葛飾区新小岩３丁目６",
      required: true,
    },
    {
      key: "phoneNumber",
      label: "電話番号",
      type: "text",
      value: "09012345678",
      required: true,
    },
    {
      key: "email",
      label: "メールアドレス",
      type: "text",
      value: "example@example.com",
      required: true,
    },
  ],
};

export const FOREIGN_INTELLECTUAL_PROPERTY_FORM_CONFIG: FormConfig = {
  layout: "horizontal",
  labelWidth: "120px",
  fields: [
    {
      key: "postalCode",
      label: "外国籍",
      type: "select",
      value: "該当する",
      options: [
        { label: "該当する", value: "該当する" },
        { label: "該当対象外", value: "該当対象外" },
      ],
      required: true,
    },
    {
      key: "name",
      label: "名前ミドルネーム",
      type: "text",
      value: "王 利艶",
      required: true,
    },
    {
      key: "residentCardNumber",
      label: "在留カードの番号",
      type: "text",
      value: "12345678901234567890",
      required: true,
    },
    {
      key: "nationality",
      label: "国籍・地域",
      type: "text",
      value: "日本",
      required: true,
    },
    {
      key: "residenceQualification",
      label: "在留資格",
      type: "select",
      value: "日本",
      options: [
        { label: "日本", value: "日本" },
        { label: "中国", value: "中国" },
        { label: "米国", value: "米国" },
        { label: "中国", value: "中国" },
      ],
      required: true,
    },
    {
      key: "residencePeriod",
      label: "在留期間",
      type: "text",
      value: "14年4ヶ月",
      required: true,
    },
    {
      key: "hasSpecialPermission",
      label: "資格外活動許可の有無",
      type: "select",
      value: "有",
      options: [
        { label: "有", value: "有" },
        { label: "無", value: "無" },
      ],
      required: true,
    },
    {
      key: "specialPermissionType",
      label: "派遣・請負就労区分",
      type: "text",
      value: "派遣",
      required: true,
    },
  ],
};

export const PERSONNEL_FORM_CONFIG: FormConfig = {
  layout: "horizontal",
  labelWidth: "120px",
  fields: [
    {
      key: "name",
      label: "名前（カタカナ）",
      type: "text",
      value: "王 利艶",
      required: true,
    },
    {
      key: "birthDate",
      label: "生年月日",
      type: "date",
      required: true,
    },
    {
      key: "age",
      label: "年齢",
      type: "text",
      value: "23",
      required: true,
    },
    {
      key: "gender",
      label: "性別",
      type: "select",
      value: "男性",
      options: [
        { label: "男性", value: "男性" },
        { label: "女性", value: "女性" },
      ],
      required: true,
    },
    {
      key: "relationship",
      label: "続柄",
      type: "select",
      value: "配偶者",
      options: [
        { label: "配偶者", value: "配偶者" },
        { label: "子供", value: "子供" },
        { label: "父母", value: "父母" },
        { label: "その他", value: "その他" },
      ],
      required: true,
      tip: "家族との関係",
    },
    {
      key: "dependentStatus",
      label: "扶養状況",
      type: "select",
      value: "扶養している",
      options: [
        { label: "扶養している", value: "扶養している" },
        { label: "扶養していない", value: "扶養していない" },
      ],
      required: true,
    },
    {
      key: "incomeTaxDependent",
      label: "所得税の扶養の加入",
      type: "radio",
      value: "加入",
      options: [
        { label: "加入", value: "加入" },
        { label: "未加入", value: "未加入" },
      ],
      required: true,
    },
    {
      key: "socialInsuranceDependent",
      label: "社会保険扶養の加入",
      type: "radio",
      value: "加入",
      options: [
        { label: "加入", value: "加入" },
        { label: "未加入", value: "未加入" },
      ],
      required: true,
    },
    {
      key: "qualificationNotice",
      label: "資格取得告知書",
      type: "radio",
      value: "有",
      options: [
        { label: "有", value: "有" },
        { label: "無", value: "無" },
      ],
      required: true,
    },
    {
      key: "incomeTaxLoss",
      label: "所得税の喪失",
      type: "radio",
      value: "有",
      options: [
        { label: "有", value: "有" },
        { label: "無", value: "無" },
      ],
      required: true,
    },
    {
      key: "socialInsuranceLoss",
      label: "社会保険扶養の喪失",
      type: "radio",
      value: "有",
      options: [
        { label: "有", value: "有" },
        { label: "無", value: "無" },
      ],
      required: true,
    },
    {
      key: "income",
      label: "所得",
      type: "text",
      value: "30万円",
      required: true,
      tip: "年間所得",
    },
    {
      key: "singleIncome",
      label: "単身収入",
      type: "radio",
      value: "有",
      options: [
        { label: "有", value: "有" },
        { label: "無", value: "無" },
      ],
      required: true,
      tip: "単身での収入の有無",
    },
    {
      key: "occupation",
      label: "職業",
      type: "text",
      value: "会社",
      required: true,
    },
    {
      key: "remarks",
      label: "備考",
      type: "textarea",
      value: "備考",
    },
    {
      key: "livingStatus",
      label: "同居・別居",
      type: "radio",
      value: "同居",
      options: [
        { label: "同居", value: "同居" },
        { label: "別居", value: "別居" },
      ],
      required: true,
    },
    {
      key: "residenceType",
      label: "住居形態",
      type: "select",
      value: "自宅",
      options: [
        { label: "自宅", value: "自宅" },
        { label: "賃貸", value: "賃貸" },
        { label: "社宅", value: "社宅" },
        { label: "その他", value: "その他" },
      ],
      required: true,
    },
    {
      key: "previousAddress",
      label: "1ヶ月前までの住所",
      type: "text",
      value: "住所1",
      required: true,
      tip: "1ヶ月前までの住所を入力",
    },
    {
      key: "fireInsurance",
      label: "火災保険の受領有無",
      type: "radio",
      value: "有",
      options: [
        { label: "有", value: "有" },
        { label: "無", value: "無" },
      ],
      required: true,
    },
  ],
};
