// 表单配置示例
import type { FormConfig } from "~/types/form";

export const BASE_FORM_CONFIG: FormConfig = {
  layout: "horizontal",
  labelWidth: "120px",
  fields: [
    {
      key: "name",
      label: "名前",
      type: "text",
      value: "王 利艳",
      required: true,
    },
    {
      key: "kanaName",
      label: "名前（カタカナ）",
      type: "text",
      value: "オウ リエン",
      required: true,
    },
    {
      key: "birthDate",
      label: "生年月日",
      type: "date",
      placeholder: "YYYY年MM月DD日",
      required: true,
    },
    {
      key: "age",
      label: "年齢",
      type: "text",
      value: "○○歳",
      required: true,
    },
    {
      key: "gender",
      label: "性別",
      type: "radio",
      value: "女性",
      options: [
        { label: "男性", value: "男性" },
        { label: "女性", value: "女性" },
      ],
      required: true,
    },
    {
      key: "hireDate",
      label: "入社日",
      type: "date",
      placeholder: "YYYY年MM月DD日",
      required: true,
    },
    {
      key: "serviceYears",
      label: "勤務年数",
      type: "text",
      value: "14年4ヶ月",
      required: true,
    },
    {
      key: "employeeNumber",
      label: "社員番号",
      type: "text",
      value: "6",
      required: true,
    },
    {
      key: "hasSpouse",
      label: "配偶者",
      type: "radio",
      value: "有",
      options: [
        { label: "有", value: "有" },
        { label: "無", value: "無" },
      ],
      required: true,
    },
    {
      key: "isSingle",
      label: "寡婦/ひとり親",
      type: "radio",
      value: "該当対象外",
      options: [
        { label: "該当する", value: "該当する" },
        { label: "該当対象外", value: "該当対象外" },
      ],
      required: true,
      tip: "寡婦は夫と死別した後婚姻していない場合、ひとり親は婚姻をしていない親の場合で、 所得や扶養親族等の条件を満たす方です。",
      tipLink: "https://www.baidu.com",
    },
    {
      key: "isDisabled",
      label: "障害",
      type: "radio",
      value: "該当対象外",
      options: [
        { label: "該当する", value: "該当する" },
        { label: "該当対象外", value: "該当対象外" },
      ],
      required: true,
      tip: "該当する障害者は所得税法上で定められています。また、特別障害者は、重度の障害のある方です。詳しくはこちら",
    },
    {
      key: "isPartTime",
      label: "勤労学生",
      type: "radio",
      value: "該当しない",
      options: [
        { label: "該当する", value: "該当する" },
        { label: "該当しない", value: "該当しない" },
      ],
      required: true,
      tip: "2026年12月31日時点で、合計所得金額が85万円以下になる見込みの学生が該当します。詳しくはこちら",
    },
    {
      key: "employmentType",
      label: "雇用形態",
      type: "select",
      value: "社員",
      options: [
        { label: "社員", value: "社員" },
        { label: "契約社員", value: "契約社員" },
        { label: "アルバイト", value: "アルバイト" },
      ],
      required: true,
      tip: "雇用「役員」にするとfreee会計に作成される給与の取引の勘定科目が「役員報酬」となります。形態",
    },
    {
      key: "position",
      label: "肩書",
      type: "text",
      value: "部長",
      required: true,
    },
    {
      key: "insuranceNumber",
      label: "基礎年金番号",
      type: "text",
      value: "S0988008886",
      required: true,
    },
  ],
};

export const RESIDENTIAL_ADDRESS_FORM_CONFIG: FormConfig = {
  layout: "horizontal",
  labelWidth: "120px",
  fields: [
    {
      key: "postalCode",
      label: "郵便番号",
      type: "text",
      value: "125-0024",
      required: true,
    },
    {
      key: "prefecture",
      label: "都道府県",
      type: "text",
      value: "東京都",
      required: true,
    },
    {
      key: "address",
      label: "市区町村以降の住所",
      type: "text",
      value: "葛飾区新小岩３丁目６",
      required: true,
    },
    {
      key: "residentialStatus",
      label: "2026年時点での世帯",
      type: "text",
      value: "本人",
      required: true,
    },
    {
      key: "residentialOwnerName",
      label: "世帯主の名前",
      type: "text",
      value: "王 利艶",
      required: true,
    },
  ],
};

export const CURRENT_RESIDENCE_FORM_CONFIG: FormConfig = {
  layout: "horizontal",
  labelWidth: "120px",
  fields: [
    {
      key: "postalCode",
      label: "郵便番号",
      type: "text",
      value: "125-0024",
      required: true,
    },
    {
      key: "prefecture",
      label: "都道府県",
      type: "text",
      value: "東京都",
      required: true,
    },
    {
      key: "address",
      label: "市区町村以降の住所",
      type: "text",
      value: "葛飾区新小岩３丁目６",
      required: true,
    },
    {
      key: "phoneNumber",
      label: "電話番号",
      type: "text",
      value: "09012345678",
      required: true,
    },
    {
      key: "email",
      label: "メールアドレス",
      type: "text",
      value: "example@example.com",
      required: true,
    },
  ],
};

export const FOREIGN_INTELLECTUAL_PROPERTY_FORM_CONFIG: FormConfig = {
  layout: "horizontal",
  labelWidth: "120px",
  fields: [
    {
      key: "postalCode",
      label: "外国籍",
      type: "select",
      value: "該当する",
      options: [
        { label: "該当する", value: "該当する" },
        { label: "該当対象外", value: "該当対象外" },
      ],
      required: true,
    },
    {
      key: "name",
      label: "名前ミドルネーム",
      type: "text",
      value: "王 利艶",
      required: true,
    },
    {
      key: "residentCardNumber",
      label: "在留カードの番号",
      type: "text",
      value: "12345678901234567890",
      required: true,
    },
    {
      key: "nationality",
      label: "国籍・地域",
      type: "text",
      value: "日本",
      required: true,
    },
    {
      key: "residenceQualification",
      label: "在留資格",
      type: "select",
      value: "日本",
      options: [
        { label: "日本", value: "日本" },
        { label: "中国", value: "中国" },
        { label: "米国", value: "米国" },
        { label: "中国", value: "中国" },
      ],
      required: true,
    },
    {
      key: "residencePeriod",
      label: "在留期間",
      type: "text",
      value: "14年4ヶ月",
      required: true,
    },
    {
      key: "hasSpecialPermission",
      label: "資格外活動許可の有無",
      type: "select",
      value: "有",
      options: [
        { label: "有", value: "有" },
        { label: "無", value: "無" },
      ],
      required: true,
    },
    {
      key: "specialPermissionType",
      label: "派遣・請負就労区分",
      type: "text",
      value: "派遣",
      required: true,
    },
  ],
};

export const PERSONNEL_FORM_CONFIG: FormConfig = {
  layout: "horizontal",
  labelWidth: "120px",
  fields: [
    {
      key: "name",
      label: "名前（カタカナ）",
      type: "text",
      value: "王 利艶",
      required: true,
    },
    {
      key: "birthDate",
      label: "生年月日",
      type: "date",
      required: true,
    },
    {
      key: "age",
      label: "年齢",
      type: "text",
      value: "23",
      required: true,
    },
    {
      key: "gender",
      label: "性別",
      type: "select",
      value: "男性",
      options: [
        { label: "男性", value: "男性" },
        { label: "女性", value: "女性" },
      ],
      required: true,
    },
    {
      key: "relationship",
      label: "続柄",
      type: "select",
      value: "配偶者",
      options: [
        { label: "配偶者", value: "配偶者" },
        { label: "子供", value: "子供" },
        { label: "父母", value: "父母" },
        { label: "その他", value: "その他" },
      ],
      required: true,
      tip: "従業員本人から見た場合の続柄を選択してください。例えば、従業員本人から見て息子であれば「子」を選択してください。",
    },
    {
      key: "dependentStatus",
      label: "扶養状況",
      type: "select",
      value: "扶養している",
      options: [
        { label: "扶養している", value: "扶養している" },
        { label: "扶養していない", value: "扶養していない" },
      ],
      required: true,
    },
    {
      key: "incomeTaxDependent",
      label: "所得税の扶養の加入",
      type: "radio",
      value: "加入",
      options: [
        { label: "加入", value: "加入" },
        { label: "未加入", value: "未加入" },
      ],
      required: true,
    },
    {
      key: "socialInsuranceDependent",
      label: "社会保険扶養の加入",
      type: "radio",
      value: "加入",
      options: [
        { label: "加入", value: "加入" },
        { label: "未加入", value: "未加入" },
      ],
      required: true,
    },
    {
      key: "qualificationNotice",
      label: "資格取得告知書",
      type: "radio",
      value: "有",
      options: [
        { label: "有", value: "有" },
        { label: "無", value: "無" },
      ],
      required: true,
    },
    {
      key: "incomeTaxLoss",
      label: "所得税の喪失",
      type: "radio",
      value: "有",
      options: [
        { label: "有", value: "有" },
        { label: "無", value: "無" },
      ],
      required: true,
    },
    {
      key: "socialInsuranceLoss",
      label: "社会保険扶養の喪失",
      type: "radio",
      value: "有",
      options: [
        { label: "有", value: "有" },
        { label: "無", value: "無" },
      ],
      required: true,
    },
    {
      key: "income",
      label: "所得",
      type: "text",
      value: "30万円",
      required: true,
      tip: "年間の収入の見込額から必要経費等を差し引いた目安額を入力してください（給与所得の場合は65万円を差し引いてください）。",
    },
    {
      key: "yearIncome",
      label: "年間収入",
      type: "text",
      value: "130万円",
      required: true,
      tip: "健康保険被扶養者（異動）届に必要となります。給与だけでなく、年金収入、傷病手当金、失業等給付も含みます。年間の目安額を入力してください。",
    },
    {
      key: "singleIncome",
      label: "単身収入",
      type: "radio",
      value: "有",
      options: [
        { label: "有", value: "有" },
        { label: "無", value: "無" },
      ],
      required: true,
      tip: "単身での収入の有無",
    },
    {
      key: "occupation",
      label: "職業",
      type: "text",
      value: "会社",
      required: true,
    },
    {
      key: "disabledabilityStatus",
      label: "障害",
      type: "textarea",
      value: "障害",
      tip: "扶養控除の対象にならない扶養親族も、障害者控除の対象。",
    },
    {
      key: "livingStatus",
      label: "同居・別居",
      type: "radio",
      value: "同居",
      options: [
        { label: "同居", value: "同居" },
        { label: "別居", value: "別居" },
      ],
      required: true,
    },
    {
      key: "residenceType",
      label: "住民票住所",
      type: "select",
      value: "自宅",
      options: [
        { label: "自宅", value: "自宅" },
        { label: "賃貸", value: "賃貸" },
        { label: "社宅", value: "社宅" },
        { label: "その他", value: "その他" },
      ],
      required: true,
    },
    {
      key: "sendAmount",
      label: "１か月あたりの仕送額",
      type: "text",
      value: "10万円",
      required: true,
      tip: "健康保険被扶養者（異動）届に必要となります。別居の場合は、１か月あたりの仕送額を記入してください。ただし、遠隔地の大学等へ進学するため別居している昼間の学生は除きます。詳しくはこちら",
    },
     {
      key: "phoneNumber",
      label: "電話番号",
      type: "text",
      value: "0000000000",
      required: true,
    },
    {
      key: "unemploymentAmount",
      label: "失業給付の受給有無",
      type: "radio",
      value: "有",
      options: [
        { label: "有", value: "有" },
        { label: "無", value: "無" },
      ],
      required: true,
    },
  ],
};

export const CONTACT_FORM_CONFIG: FormConfig = {
  layout: 'horizontal',
  labelWidth: '120px',
  fields: [
    {
      key: 'relationship',
      label: '続柄',
      type: 'select',
      options: [
        { label: '本人', value: '本人' },
        { label: '配偶者', value: '配偶者' },
        { label: '子供', value: '子供' },
        { label: '父母', value: '父母' },
        { label: '兄弟姉妹', value: '兄弟姉妹' },
        { label: 'その他', value: 'その他' },
      ],
      required: true,
    },
    {
      key: 'name',
      label: '名前（カタカナ）',
      type: 'text',
      required: true,
      placeholder: '例：タナカ タロウ',
    },
    {
      key: 'phone',
      label: '電話番号',
      type: 'text',
      required: true,
      placeholder: '例：0123-45-6789',
    },
    {
      key: 'email',
      label: 'メールアドレス',
      type: 'text',
      required: true,
      placeholder: '例：example@example.com',
    },
    {
      key: 'prefecture',
      label: '都道府県',
      type: 'select',
      options: [
        { label: '北海道', value: '北海道' },
        { label: '青森県', value: '青森県' },
        { label: '岩手県', value: '岩手県' },
        { label: '宮城県', value: '宮城県' },
        { label: '秋田県', value: '秋田県' },
        { label: '山形県', value: '山形県' },
        { label: '福島県', value: '福島県' },
        { label: '茨城県', value: '茨城県' },
        { label: '栃木県', value: '栃木県' },
        { label: '群馬県', value: '群馬県' },
        { label: '埼玉県', value: '埼玉県' },
        { label: '千葉県', value: '千葉県' },
        { label: '東京都', value: '東京都' },
        { label: '神奈川県', value: '神奈川県' },
        { label: '新潟県', value: '新潟県' },
        { label: '富山県', value: '富山県' },
        { label: '石川県', value: '石川県' },
        { label: '福井県', value: '福井県' },
        { label: '山梨県', value: '山梨県' },
        { label: '長野県', value: '長野県' },
        { label: '岐阜県', value: '岐阜県' },
        { label: '静岡県', value: '静岡県' },
        { label: '愛知県', value: '愛知県' },
        { label: '三重県', value: '三重県' },
        { label: '滋賀県', value: '滋賀県' },
        { label: '京都府', value: '京都府' },
        { label: '大阪府', value: '大阪府' },
        { label: '兵庫県', value: '兵庫県' },
        { label: '奈良県', value: '奈良県' },
        { label: '和歌山県', value: '和歌山県' },
        { label: '鳥取県', value: '鳥取県' },
        { label: '島根県', value: '島根県' },
        { label: '岡山県', value: '岡山県' },
        { label: '広島県', value: '広島県' },
        { label: '山口県', value: '山口県' },
        { label: '徳島県', value: '徳島県' },
        { label: '香川県', value: '香川県' },
        { label: '愛媛県', value: '愛媛県' },
        { label: '高知県', value: '高知県' },
        { label: '福岡県', value: '福岡県' },
        { label: '佐賀県', value: '佐賀県' },
        { label: '長崎県', value: '長崎県' },
        { label: '熊本県', value: '熊本県' },
        { label: '大分県', value: '大分県' },
        { label: '宮崎県', value: '宮崎県' },
        { label: '鹿児島県', value: '鹿児島県' },
        { label: '沖縄県', value: '沖縄県' },
      ],
      required: true,
    },
    {
      key: 'address1',
      label: '都道府村以降の住所',
      type: 'text',
      required: true,
      placeholder: '例：○○市○○区○○町○○番地',
    },
    {
      key: 'address2',
      label: '市区町村以降の住所（カタカナ）',
      type: 'text',
      required: true,
      placeholder: '例：○○シ○○ク○○チョウ○○バンチ',
    },
  ],
};
